[package]
name = "visualization"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"

[[bin]]
name = "visualization"
path = "main/main.rs"

[lints]
workspace = true

[dependencies]
symplectic.workspace = true
euclidean-polytopes.workspace = true
nalgebra.workspace = true
num-rational.workspace = true
num-traits.workspace = true
serde.workspace = true
serde_json.workspace = true
