#!/usr/bin/env python3
"""
Ablation study analysis: compare HK2017 adjacency graph pruning variants (A-axis).

A0 (unpruned) → A1 (vertex adjacency) → A2 (directed ω₀) → A3 (Reeb-flow feasibility).
Each variant adds strictly more pruning than the previous.

Input: crates/dev-algorithm-comparison/ablation/ablation.jsonl (generated by ablation.rs)
Output: crates/dev-algorithm-comparison/ablation/ablation_timing.png (timing comparison figure)
"""

import json
import sys
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
from figure_config import setup, TEXT_WIDTH
setup()

EXPERIMENT_DIR = Path(__file__).resolve().parent
DATA_PATH = EXPERIMENT_DIR / "ablation.jsonl"
FIGURE_PATH = EXPERIMENT_DIR / "ablation_timing.png"

VARIANTS = ["a0_unpruned", "a1_vertex_adj", "a2_omega_directed", "a3_reeb_feasible"]
VARIANT_LABELS = {
    "a0_unpruned": "A0 unpruned",
    "a1_vertex_adj": "A1 vertex adj",
    "a2_omega_directed": "A2 directed ω₀",
    "a3_reeb_feasible": "A3 Reeb feasible",
}
GROUPS = ["random_generic", "random_lagrangian", "regression", "non_simple"]


# ============================================================================
# Data loading
# ============================================================================

def load_dataset():
    """Load ablation JSONL. Returns list of entry dicts."""
    if not DATA_PATH.exists():
        print(f"Dataset not found: {DATA_PATH}", file=sys.stderr)
        print(
            "Run: cd experiments && cargo run --bin ablation --release",
            file=sys.stderr,
        )
        sys.exit(1)

    entries = []
    with open(DATA_PATH) as f:
        for line in f:
            line = line.strip()
            if line:
                entries.append(json.loads(line))
    return entries


# ============================================================================
# Agreement check
# ============================================================================

def check_agreement(entries):
    """
    Check that all variants agree on capacity.
    Returns (n_disagreements, disagreement_list).
    """
    by_polytope = defaultdict(dict)
    for e in entries:
        by_polytope[e["polytope_name"]][e["variant"]] = e

    disagreements = []
    for name, variants in sorted(by_polytope.items()):
        if len(variants) < 2:
            continue
        caps = {v: d["capacity"] for v, d in variants.items()}
        values = list(caps.values())
        max_diff = max(abs(a - b) for a in values for b in values)
        if max_diff > 1e-5:
            disagreements.append({
                "polytope": name,
                "group": next(iter(variants.values()))["group"],
                "facets": next(iter(variants.values()))["facet_count"],
                **caps,
                "max_diff": max_diff,
            })

    return len(disagreements), disagreements


# ============================================================================
# Summary tables
# ============================================================================

def print_agreement_table(entries):
    """Print per-polytope capacity agreement across all variants."""
    by_polytope = defaultdict(dict)
    for e in entries:
        by_polytope[e["polytope_name"]][e["variant"]] = e

    active_variants = sorted(set(e["variant"] for e in entries))
    hdr_caps = " ".join(f"{VARIANT_LABELS.get(v, v):>12}" for v in active_variants)
    print("\n=== Capacity Agreement: all variants ===")
    print(f"{'Polytope':<35} {'F':>3} {hdr_caps} {'max|diff|':>10} {'Status'}")
    print("-" * (55 + 13 * len(active_variants)))

    n_ok = 0
    n_fail = 0
    for name in sorted(by_polytope.keys()):
        variants = by_polytope[name]
        f = next(iter(variants.values()))["facet_count"]

        caps = [variants.get(v, {}).get("capacity", float("nan")) for v in active_variants]
        diff = max(abs(a - b) for a in caps for b in caps)
        status = "OK" if diff < 1e-5 else "DISAGREE"
        if diff < 1e-5:
            n_ok += 1
        else:
            n_fail += 1

        cap_str = " ".join(f"{c:>12.8f}" for c in caps)
        flag = " *" if diff >= 1e-5 else ""
        print(f"{name:<35} {f:>3} {cap_str} {diff:>10.2e} {status}{flag}")

    print("-" * (55 + 13 * len(active_variants)))
    print(f"Agreement: {n_ok}/{n_ok + n_fail} polytopes OK")
    if n_fail > 0:
        print(f"DISAGREEMENTS: {n_fail} polytopes differ by > 1e-5")
    return n_fail


def print_timing_table(entries):
    """Print timing comparison table per group and F, all variants."""
    by_group_f_variant = defaultdict(list)
    for e in entries:
        if e["group"] == "regression":
            continue
        key = (e["group"], e["facet_count"], e["variant"])
        by_group_f_variant[key].append(e["time_ms"])

    group_f_pairs = sorted(set(
        (g, f) for (g, f, _v) in by_group_f_variant
    ))

    active_variants = [v for v in VARIANTS if any(
        (g, f, v) in by_group_f_variant for g, f in group_f_pairs
    )]

    print("\n=== Timing Comparison: all variants ===")
    hdr = f"{'Group':<20} {'F':>3}"
    for v in active_variants:
        hdr += f" {VARIANT_LABELS.get(v, v) + ' (ms)':>14}"
    hdr += f" {'A1/A0':>7} {'A3/A0':>7} {'N':>4}"
    print(hdr)
    print("-" * len(hdr))

    for group, f in group_f_pairs:
        means = {}
        row = f"{group:<20} {f:>3}"
        for v in active_variants:
            times = by_group_f_variant.get((group, f, v), [])
            if times:
                m = float(np.mean(times))
                means[v] = m
                row += f" {m:>14.1f}"
            else:
                row += f" {'--':>14}"

        # Speedup ratios relative to A0
        m0 = means.get("a0_unpruned")
        m1 = means.get("a1_vertex_adj")
        m4 = means.get("a3_reeb_feasible")
        ratio_a1 = f"{m0/m1:.1f}x" if m0 and m1 else "--"
        ratio_a3 = f"{m0/m4:.1f}x" if m0 and m4 else "--"
        n = len(by_group_f_variant.get((group, f, active_variants[0]), []))
        row += f" {ratio_a1:>7} {ratio_a3:>7} {n:>4}"
        print(row)

    print()


def print_iteration_table(entries):
    """Print iteration count comparison (measures pruning effectiveness)."""
    by_group_f_variant = defaultdict(list)
    for e in entries:
        if e["group"] == "regression":
            continue
        key = (e["group"], e["facet_count"], e["variant"])
        by_group_f_variant[key].append(e["iterations"])

    group_f_pairs = sorted(set(
        (g, f) for (g, f, _v) in by_group_f_variant
    ))

    active_variants = [v for v in VARIANTS if any(
        (g, f, v) in by_group_f_variant for g, f in group_f_pairs
    )]

    print("\n=== Iteration Counts: pruning effectiveness ===")
    hdr = f"{'Group':<20} {'F':>3}"
    for v in active_variants:
        hdr += f" {VARIANT_LABELS.get(v, v):>12}"
    hdr += f" {'A1/A0':>8} {'A3/A0':>8}"
    print(hdr)
    print("-" * len(hdr))

    for group, f in group_f_pairs:
        means = {}
        row = f"{group:<20} {f:>3}"
        for v in active_variants:
            iters = by_group_f_variant.get((group, f, v), [])
            if iters:
                m = float(np.mean(iters))
                means[v] = m
                row += f" {m:>12.0f}"
            else:
                row += f" {'--':>12}"

        m0 = means.get("a0_unpruned")
        m1 = means.get("a1_vertex_adj")
        m4 = means.get("a3_reeb_feasible")
        r1 = f"{m1/m0:.3f}" if m0 and m1 else "--"
        r4 = f"{m4/m0:.3f}" if m0 and m4 else "--"
        row += f" {r1:>8} {r4:>8}"
        print(row)

    print()


def print_regression_table(entries):
    """Print regression cases: capacity vs expected."""
    regression = [e for e in entries if e["group"] == "regression"]
    if not regression:
        return

    print("=== Regression Cases ===")
    print(f"{'Polytope':<35} {'Variant':<15} {'Capacity':>12} {'Time (ms)':>10} {'Iters':>10}")
    print("-" * 85)

    for e in sorted(regression, key=lambda x: (x["polytope_name"], x["variant"])):
        print(
            f"{e['polytope_name']:<35} {e['variant']:<15} {e['capacity']:>12.8f} "
            f"{e['time_ms']:>10.2f} {e['iterations']:>10}"
        )
    print()


# ============================================================================
# Non-simple polytopes: A2 vs A3 comparison
# ============================================================================

def print_nonsimple_table(entries):
    """Print A2 vs A3 iteration comparison for non-simple polytopes."""
    # Include both the "non_simple" group and the original regression cut simplex
    nonsimple = [
        e for e in entries
        if e["group"] == "non_simple" or e["polytope_name"] == "regression_cut_simplex"
    ]
    if not nonsimple:
        return

    by_polytope = defaultdict(dict)
    for e in nonsimple:
        by_polytope[e["polytope_name"]][e["variant"]] = e

    print("\n=== Non-Simple Polytopes: A2 vs A3 ===")
    print(f"{'Polytope':<35} {'F':>3} {'A2 iters':>10} {'A3 iters':>10} {'Pruned':>8} {'%':>6}")
    print("-" * 78)

    for name in sorted(by_polytope.keys()):
        variants = by_polytope[name]
        f = next(iter(variants.values()))["facet_count"]
        a2 = variants.get("a2_omega_directed", {}).get("iterations", 0)
        a3 = variants.get("a3_reeb_feasible", {}).get("iterations", 0)
        pruned = a2 - a3
        pct = 100.0 * pruned / a2 if a2 > 0 else 0.0
        marker = " *" if pruned > 0 else ""
        print(f"{name:<35} {f:>3} {a2:>10} {a3:>10} {pruned:>8} {pct:>5.1f}%{marker}")

    print()


# ============================================================================
# Scaling exponent fit
# ============================================================================

def fit_scaling_exponent(entries):
    """Fit A2/A0 iteration ratio as exponential in F for random_generic polytopes.

    Model: iterations_A2 / iterations_A0 = a * exp(b * F)
    Equivalently: log(ratio) = log(a) + b * F  (linear fit in log space).

    Returns (a, b, r_squared) or None if insufficient data.
    """
    generic = [e for e in entries if e["group"] == "random_generic"]
    by_f_variant = defaultdict(lambda: defaultdict(list))
    for e in generic:
        by_f_variant[e["facet_count"]][e["variant"]].append(e["iterations"])

    f_vals = sorted(by_f_variant.keys())
    if len(f_vals) < 3:
        print("\n=== Scaling Exponent: insufficient data (need ≥3 F values) ===")
        return None

    ratios = []
    f_points = []
    for f in f_vals:
        a0_iters = by_f_variant[f].get("a0_unpruned", [])
        a2_iters = by_f_variant[f].get("a2_omega_directed", [])
        if a0_iters and a2_iters:
            mean_a0 = float(np.mean(a0_iters))
            mean_a2 = float(np.mean(a2_iters))
            if mean_a0 > 0 and mean_a2 > 0:
                ratios.append(mean_a2 / mean_a0)
                f_points.append(f)

    if len(f_points) < 3:
        print("\n=== Scaling Exponent: insufficient valid ratios ===")
        return None

    f_arr = np.array(f_points, dtype=float)
    log_ratios = np.log(np.array(ratios))

    # Linear fit: log(ratio) = b * F + log(a)
    coeffs = np.polyfit(f_arr, log_ratios, 1)
    b = coeffs[0]
    log_a = coeffs[1]
    a = np.exp(log_a)

    # R² for goodness of fit
    predicted = np.polyval(coeffs, f_arr)
    ss_res = np.sum((log_ratios - predicted) ** 2)
    ss_tot = np.sum((log_ratios - np.mean(log_ratios)) ** 2)
    r_squared = 1.0 - ss_res / ss_tot if ss_tot > 0 else 0.0

    print("\n=== Scaling Exponent: A2/A0 iteration ratio vs F ===")
    print(f"Model: ratio = a * exp(b * F)")
    print(f"  a = {a:.4f}")
    print(f"  b = {b:.4f}  (scaling exponent)")
    print(f"  R² = {r_squared:.6f}")
    print(f"  Data points: F = {f_points}")
    print(f"  Ratios:      {[f'{r:.4f}' for r in ratios]}")
    print()

    return a, b, r_squared


# ============================================================================
# Figure
# ============================================================================

def plot_timing(entries):
    """Timing comparison figure: all variants per group and F."""
    groups_to_plot = ["random_generic", "random_lagrangian"]
    group_display = {
        "random_generic": "Random generic polytopes",
        "random_lagrangian": "Random Lagrangian products",
    }

    fig, axes = plt.subplots(1, 2, figsize=(TEXT_WIDTH, 3.5), sharey=False)

    colors = {
        "a0_unpruned": "#e08020",
        "a1_vertex_adj": "#2060c0",
        "a2_omega_directed": "#20a040",
        "a3_reeb_feasible": "#a02080",
    }
    markers = {
        "a0_unpruned": "^",
        "a1_vertex_adj": "o",
        "a2_omega_directed": "s",
        "a3_reeb_feasible": "D",
    }

    for ax, group in zip(axes, groups_to_plot):
        group_entries = [e for e in entries if e["group"] == group]

        by_variant_f = defaultdict(lambda: defaultdict(list))
        for e in group_entries:
            by_variant_f[e["variant"]][e["facet_count"]].append(e["time_ms"])

        for variant in VARIANTS:
            f_vals = sorted(by_variant_f[variant].keys())
            if not f_vals:
                continue

            means = [float(np.mean(by_variant_f[variant][f])) for f in f_vals]
            stds = [float(np.std(by_variant_f[variant][f], ddof=1)) for f in f_vals]

            ax.errorbar(
                f_vals,
                means,
                yerr=stds,
                marker=markers[variant],
                color=colors[variant],
                linewidth=2,
                markersize=6,
                capsize=4,
                capthick=1.5,
                elinewidth=1.5,
                alpha=0.9,
                label=f"{VARIANT_LABELS[variant]}",
            )

        ax.set_yscale("log")
        ax.set_xlabel("Facet count $F$")
        ax.set_ylabel("Time (ms)")
        ax.set_title(group_display[group])
        ax.grid(True, alpha=0.3, which="both")
        # Integer x-ticks for facet count
        all_f = sorted(set(
            e["facet_count"] for e in entries if e["group"] == group
        ))
        ax.set_xticks(all_f)

    fig.suptitle(
        "Adjacency pruning: timing by facet count (mean $\\pm$ std, $n=5$)",
    )
    # Shared legend from first axis (both panels have same entries)
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=4, bbox_to_anchor=(0.5, -0.02))
    fig.tight_layout(rect=[0, 0.08, 1, 0.95])
    fig.savefig(FIGURE_PATH)
    plt.close(fig)
    print(f"Figure: {FIGURE_PATH}")


# ============================================================================
# Main
# ============================================================================

def main():
    entries = load_dataset()
    n_total = len(entries)
    n_polytopes = len(set(e["polytope_name"] for e in entries))
    n_variants = len(set(e["variant"] for e in entries))
    print(f"Loaded {n_total} entries ({n_polytopes} polytopes x {n_variants} variants)")
    print(f"Groups: {sorted(set(e['group'] for e in entries))}")

    print_regression_table(entries)
    n_disagree = print_agreement_table(entries)
    print_timing_table(entries)
    print_iteration_table(entries)
    print_nonsimple_table(entries)
    fit_scaling_exponent(entries)
    plot_timing(entries)

    if n_disagree > 0:
        print(f"\nFAILURE: {n_disagree} disagreements found.", file=sys.stderr)
        sys.exit(1)
    else:
        print("\nAll variants agree. Ablation study complete.")


if __name__ == "__main__":
    main()
