[package]
name = "dev-numerical-analysis"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "num-error-bounds"
path = "error-bounds/main.rs"

[[bin]]
name = "num-collect-poly"
path = "error-bounds/collect_poly.rs"

[[bin]]
name = "num-q-error"
path = "q-error/main.rs"

[[bin]]
name = "num-kkt-inertia"
path = "kkt-inertia/main.rs"

[[bin]]
name = "num-unknown-predicates"
path = "unknown-predicates/main.rs"

[[bin]]
name = "num-algebraic-exactness"
path = "algebraic-exactness/main.rs"

[[test]]
name = "verify_numerics_tests"
path = "error-bounds/tests.rs"

[lints]
workspace = true

[dependencies]
symplectic.workspace = true
nalgebra.workspace = true
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
rand_chacha.workspace = true
rand_distr.workspace = true
num-bigint.workspace = true
num-rational.workspace = true
num-traits.workspace = true
good_lp.workspace = true
