[package]
name = "exp-performance"
version = "0.1.0"
publish = false
edition = "2021"

[[bin]]
name = "hk2017-pruned-f64"
path = "src/bin/hk2017_pruned_f64.rs"

[[bin]]
name = "hk2017-cycle-enumeration"
path = "src/bin/hk2017_cycle_enumeration.rs"

[[bin]]
name = "capacity-paths-random"
path = "src/bin/capacity_paths_random.rs"

[[bin]]
name = "capacity-profile-one"
path = "src/bin/capacity_profile_one.rs"

[[bin]]
name = "capacity-route-costs"
path = "src/bin/capacity_route_costs.rs"

[lints]
workspace = true

[dependencies]
symplectic.workspace = true
euclidean-polytopes.workspace = true
exp-dev-quadratic-program = { path = "../dev-quadratic-program" }
nalgebra.workspace = true
serde.workspace = true
serde_json.workspace = true
num-rational.workspace = true
rand.workspace = true
rand_chacha.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
