[package]
name = "dev-gradient"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "dev_numerics"
path = "numerics/main.rs"

[[bin]]
name = "dev_numerics_edge_cases"
path = "numerics-edge-cases/main.rs"

[[bin]]
name = "dev_numerics_subdifferential"
path = "numerics-subdifferential/main.rs"

[lints]
workspace = true

[dependencies]
symplectic.workspace = true
euclidean-polytopes.workspace = true
nalgebra.workspace = true
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
rand_chacha.workspace = true
rand_distr.workspace = true
num-bigint.workspace = true
num-rational.workspace = true
num-traits.workspace = true
good_lp.workspace = true
