[package]
name = "exp-combinatorial-cells"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "cell-boundary-characterization"
path = "boundary-characterization/run.rs"

[[bin]]
name = "cell-widths"
path = "cell-widths/run.rs"

[[bin]]
name = "cell-convexity"
path = "convexity/run.rs"

[[bin]]
name = "cell-multiple-crossings"
path = "multiple-crossings/run.rs"

[[bin]]
name = "cell-omega"
path = "omega-hypothesis/run.rs"

[lints]
workspace = true

[dependencies]
database = { path = "../database" }
symplectic.workspace = true
nalgebra.workspace = true
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
rand_chacha.workspace = true
rand_distr.workspace = true
num-bigint.workspace = true
num-rational.workspace = true
num-traits.workspace = true
good_lp.workspace = true
