[package]
name = "exp-dev-sys-prediction"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dev-sys-prediction-panel"
path = "produce/dataset-panel.rs"

[[bin]]
name = "dev-sys-prediction-produce"
path = "produce/prediction-cloud.rs"

[[bin]]
name = "dev-sysext-sigma-line-probe"
path = "sysext-sigma-line-probe/main.rs"

[[bin]]
name = "dev-sysext-beta-boundary-scan"
path = "sysext-beta-boundary-scan/main.rs"

[lints]
workspace = true

[dependencies]
exp-dev-gradient-ascent = { path = "../dev-gradient-ascent" }
exp-sys-landscape = { path = "../sys-landscape" }
good_lp.workspace = true
nalgebra.workspace = true
num-rational.workspace = true
serde.workspace = true
serde_json.workspace = true
symplectic.workspace = true
