[package]
name = "hk2017"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { workspace = true }
geom = { path = "../geom" }
rand = { workspace = true }
rand_chacha = { workspace = true }
rand_distr = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
datasets = { path = "../datasets" }
rand = { workspace = true }
rand_chacha = { workspace = true }
