[package]
name = "exp-algorithm-comparison"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cmp-ablation"
path = "ablation/run.rs"

[[bin]]
name = "cmp-benchmark"
path = "benchmark/run.rs"

[[bin]]
name = "cmp-benchmark-profile"
path = "benchmark/profile.rs"

[lints]
workspace = true

[dependencies]
symplectic.workspace = true
nalgebra.workspace = true
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
rand_chacha.workspace = true
rand_distr.workspace = true
num-bigint.workspace = true
num-rational.workspace = true
num-traits.workspace = true
good_lp.workspace = true
