"""
Goal: Analyze gradient direction change at combinatorial boundaries.
Input: crates/exp-combinatorial-cells/boundary-characterization/combinatorial-boundaries-gradient.jsonl
       crates/exp-combinatorial-cells/boundary-characterization/combinatorial-boundaries-anatomy.jsonl
       crates/exp-combinatorial-cells/cell-widths/combinatorial-boundaries-profiling.jsonl
Output: crates/exp-combinatorial-cells/gradient-discontinuity/*.png

Note: Data is generated by boundary-characterization/run.rs (cell-boundary-characterization binary).
"""

import json
import sys
from collections import defaultdict
from pathlib import Path
import numpy as np

EXPERIMENT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(EXPERIMENT_DIR.parent.parent))
from figure_config import (
    setup, FIGSIZE_SINGLE, SCATTER_SIZE,
    FONT_SIZE_SMALL,
)
setup()

import matplotlib.pyplot as plt

# ============================================================================
# Data loading
# ============================================================================

def load_jsonl(path):
    rows = []
    with open(path) as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


BOUNDARY_CHAR_DIR = EXPERIMENT_DIR.parent / "boundary-characterization"
CELL_WIDTHS_DIR = EXPERIMENT_DIR.parent / "cell-widths"

gradient = load_jsonl(BOUNDARY_CHAR_DIR / "combinatorial-boundaries-gradient.jsonl")
anatomy = load_jsonl(BOUNDARY_CHAR_DIR / "combinatorial-boundaries-anatomy.jsonl")

# Load profiling data from cell-widths experiment for gradient-cell alignment
profiling_path = CELL_WIDTHS_DIR / "combinatorial-boundaries-profiling.jsonl"
profiling = []
if profiling_path.exists():
    profiling = load_jsonl(profiling_path)

print(f"Loaded: {len(gradient)} gradient, {len(anatomy)} anatomy, "
      f"{len(profiling)} profiling rows")

# ============================================================================
# Figure 1: Gradient angle change histogram (gradient)
# ============================================================================

if gradient:
    angles = [row["gradient_angle_change_deg"] for row in gradient
              if not np.isnan(row["gradient_angle_change_deg"])]
    if angles:
        fig, ax = plt.subplots(figsize=FIGSIZE_SINGLE)
        ax.hist(angles, bins=50, color="#E91E63", alpha=0.7)
        ax.set_xlabel("Gradient angle change (degrees)")
        ax.set_ylabel("Count")
        ax.set_title("Gradient direction change at first boundary")
        ax.axvline(np.median(angles), color="red", ls="--", lw=1,
                   label=f"Median: {np.median(angles):.4f}" + r"$^\circ$")
        ax.legend()
        fig.savefig(EXPERIMENT_DIR / "boundary_gradient_angle.png")
        plt.close()
        print("  boundary_gradient_angle.png")

# ============================================================================
# Figure 2: Gradient-cell alignment (anatomy + profiling)
# ============================================================================

if profiling:
    facet_median_tmax = defaultdict(dict)
    for r in profiling:
        if r["t_max"] < 100:
            key = (r["polytope_name"], r["facet_index"])
            facet_median_tmax[r["polytope_name"]][r["facet_index"]] = \
                facet_median_tmax[r["polytope_name"]].get(r["facet_index"], [])
            facet_median_tmax[r["polytope_name"]][r["facet_index"]].append(r["t_max"])

    # Compute median per facet
    for pname in facet_median_tmax:
        for k in facet_median_tmax[pname]:
            vals = facet_median_tmax[pname][k]
            facet_median_tmax[pname][k] = np.median(vals)

    grad_tmax = []
    min_cell_width = []
    for r in anatomy:
        if r["direction_type"] == "gradient" and r["t_max"] < 100:
            pname = r["polytope_name"]
            if pname in facet_median_tmax:
                widths = list(facet_median_tmax[pname].values())
                if widths:
                    grad_tmax.append(r["t_max"])
                    min_cell_width.append(min(widths))

    if grad_tmax and min_cell_width:
        fig, ax = plt.subplots(figsize=FIGSIZE_SINGLE)
        ax.scatter(min_cell_width, grad_tmax, s=SCATTER_SIZE, alpha=0.5,
                   c="#E91E63", edgecolors="none")
        ax.set_xlabel("Min per-facet median cell width")
        ax.set_ylabel(r"Gradient direction $t_{\max}$")
        ax.set_title("Gradient boundary distance vs narrowest cell width")

        # Correlation
        corr = np.corrcoef(min_cell_width, grad_tmax)[0, 1]
        ax.text(0.05, 0.95, f"r = {corr:.3f}", transform=ax.transAxes, va="top",
                fontsize=FONT_SIZE_SMALL)
        fig.savefig(EXPERIMENT_DIR / "gradient_cell_alignment.png")
        plt.close()
        print("  gradient_cell_alignment.png")

# ============================================================================
# Summary statistics
# ============================================================================

print("\n=== Summary Statistics ===")

if gradient:
    angles_all = [r["gradient_angle_change_deg"] for r in gradient
                  if not np.isnan(r["gradient_angle_change_deg"])]
    if angles_all:
        print(f"Gradient angle change: median={np.median(angles_all):.4f} deg, "
              f"max={max(angles_all):.1f} deg")

print("\nDone.")
