[package]
name = "exp-polytope-datasets"
version = "0.1.0"
publish = false
edition = "2021"

[[bin]]
name = "sys-dataset-random"
path = "random.rs"

[[bin]]
name = "sys-dataset-random-product"
path = "random-product.rs"

[[bin]]
name = "sys-datascience-produce"
path = "main.rs"

[lints]
workspace = true

[dependencies]
exp-sys-landscape = { path = "../sys-landscape" }
symplectic.workspace = true
euclidean-polytopes.workspace = true
nalgebra.workspace = true
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
rand_chacha.workspace = true
rand_distr.workspace = true
num-bigint.workspace = true
num-rational.workspace = true
num-traits.workspace = true
blake3.workspace = true
good_lp.workspace = true
rayon.workspace = true
sha2 = "0.10"
