[package]
name = "euclidean-polytopes"
version = "0.1.0"
edition = "2021"

[dependencies]
algebraic-numbers.workspace = true
nalgebra.workspace = true
num-bigint.workspace = true
num-integer.workspace = true
num-rational.workspace = true
num-traits.workspace = true
rand.workspace = true
rand_distr.workspace = true
tracing.workspace = true

[dev-dependencies]
proptest.workspace = true
rand_chacha.workspace = true
