[workspace]
resolver = "2"
members = [
    "geom",
    "hk2017",
    "billiard",
    "tube",
    "datasets",
]

[workspace.dependencies]
nalgebra = { version = "0.33", features = ["serde-serialize"] }
proptest = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
rand_chacha = "0.3"
rand_distr = "0.4"

[profile.release]
debug = true
