[package]
name = "datasets"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "datasets"
path = "src/main.rs"

[[bin]]
name = "benchmark"
path = "src/bin/benchmark.rs"

[[bin]]
name = "lagrangian_sweep"
path = "src/bin/lagrangian_sweep.rs"

[[bin]]
name = "random_sweep"
path = "src/bin/random_sweep.rs"

[[bin]]
name = "random_product_sweep"
path = "src/bin/random_product_sweep.rs"

[[bin]]
name = "correctness"
path = "src/bin/correctness.rs"

[dependencies]
nalgebra = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rand_distr = { workspace = true }
geom = { path = "../geom" }
hk2017 = { path = "../hk2017" }
billiard = { path = "../billiard" }
tube = { path = "../tube" }

[dev-dependencies]
proptest = { workspace = true }
